version: "3.8"

services:
  # YA NO NECESITAMOS EL SERVICIO TRAEFIK
  # Lo borramos porque usaremos el del profesor.

  # ---------------------------------------
  # TU APP DEL GRUPO 7
  # ---------------------------------------
  grupo-7:
    build: .
    container_name: grupo-7-app
    restart: always
    networks:
      - traefik-public # <--- Nos conectamos a la red existente
    labels:
      # Habilitar Traefik
      - "traefik.enable=true"
      
      # --- ROUTER ---
      # Tu dominio
      - "traefik.http.routers.grupo-7.rule=Host(`grupo-7.byronrm.com`)"
      - "traefik.http.routers.grupo-7.entrypoints=websecure"
      
      # IMPORTANTE: El nombre del resolver del profesor.
      # Usualmente es 'le' o 'myresolver'. Probemos con 'le' primero.
      # Si no carga el SSL, intenta cambiar 'le' por 'http' o 'myresolver'.
      - "traefik.http.routers.grupo-7.tls.certresolver=le"
      
      # --- SERVICIO ---
      # Puerto interno de tu Flask (5000)
      - "traefik.http.services.grupo-7.loadbalancer.server.port=5000"

# Definimos la red externa
networks:
  traefik-public:
    external: true # <--- Le decimos que NO la cree, que ya existe